# Generated by Django 3.2.3 on 2021-07-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildCron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='no_of_license',
            field=models.IntegerField(),
        ),
    ]
