# Generated by Django 3.2.4 on 2021-07-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildCron', '0003_alter_licenses_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='Admin_id',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_id',
        ),
        migrations.RemoveField(
            model_name='faqs',
            name='faq_id',
        ),
        migrations.RemoveField(
            model_name='licenses',
            name='license_id',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='query_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='roles_id',
        ),
        migrations.RemoveField(
            model_name='siteinstruction',
            name='site_id',
        ),
    ]
