# Generated by Django 3.2.4 on 2021-07-21 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildCron', '0004_auto_20210720_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_id',
        ),
    ]
