# Generated by Django 3.2.5 on 2021-08-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildCron', '0005_remove_material_material_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='end_date',
            field=models.DateField(),
        ),
    ]
