# Generated by Django 3.2.5 on 2021-08-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildCron', '0006_alter_registration_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('security_level', models.TextField()),
            ],
        ),
    ]
